### ISSUE TITLE
can not open the camera,when running  "run.sh"

### ISSUE THREAD

**Issue by bjthemost** [OAID/FaceRecognition2#1]
on AIO-RK3399 board, USB camera.

------------------------
 VideoCapture capture("/dev/video1");///CV_CAP_XIAPI);//0);

    capture.open(DeviceID);
    if (!capture.isOpened()) { //判断能够打开摄像头
        cout << "can not open the camera" << endl;
        cin.get();
        exit(1);
    }

**Comment by xcls1117** [comment]
@bjthemost  check the VideoDeviceID in demo.conf if your video id is 1.
Also, for VideoCapture class, you should use 
`VideoCapture capture(1);`
or
`VideoCapture capture;
capture.open(1); `
or open a video file
`VideoCapture capture("*.avi");`
